### PR TITLE
Update Pressure_WW_SLL.py

### PR DESCRIPTION
**Pull request by milenasingletary**
I've added a few updates to this script to account for values below 1.

Still a work in progress. There is something royally wrong with area calculations as in the export percentages are well above 100, so i'll be working that out and may need some insight if you have any.

### CODE REVIEW

**Comment by kharrison89** [comment]
If you step through the createTS mat function, you will notice that the you come up with an array of only 211 for plantarSensel. There are 220 sensels on the plantar insole, so you should double check the columns you are extracting from dat.

Once you have all 220 sensels, you can count how many sensels are in each row for each section (e.g. heel). you can count sensels in the window on the xsensor software you use to create templates. Make sure when you are calculating the percent area in the code, you are dividing by the corrent number of total sensels for each section. Note, this can be easily confused because python 0 indexes so always double check you are counting the correct rows. 

Let me know if you have any questions on this!

**Comment by milenasingletary** [comment]
updated the number of sensels and was missing division by the number of frames for the contact areas. It looks good now.

**Comment by kharrison89** [comment]
One more thing, for the contact areas, you are adding up the nonzero sensels for each from from landing to landing +100, so you will have to divide by this number of frames to get the average contact area.

**Review by kharrison89 — COMMENTED** [review]
Looks good!

**Review by kharrison89 — APPROVED** [review]

**Pull request merged**
